on:
  push:
    branches:
      - main
env:
  CONTAINER_IMAGE: secretcolossus/${{github.event.repository.name}}:latest
jobs:
  build-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub login
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Build image
        run: docker build -t $CONTAINER_IMAGE .
      - name: Push to Docker Hub
        run: docker push $CONTAINER_IMAGE
